[package]
name = "fixx"
version = "0.0.0-git"
edition = "2021"
repository = "https://github.com/NuschtOS/ixx/"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
libixx = { path = "../libixx" }
wasm-bindgen = "0.2"
